# version: '3.8'
x-airflow-common: &airflow-common
  
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.0}
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # --- [은비의 요청!] .env 파일의 AWS 정보를 Airflow 시스템 변수로 주입 ---
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    TZ: 'Asia/Seoul'
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'Asia/Seoul'
    # ------------------------------------------------------------------
    _PIP_ADDITIONAL_REQUIREMENTS: 'pytchat requests apache-airflow-providers-amazon boto3 pyyaml'
  volumes:
    # --- [은비의 구조 반영!] 호스트의 airflow/dags 폴더를 컨테이너에 연결 ---
    - ./airflow/dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./config:/opt/airflow/config
    - ./plugins:/opt/airflow/plugins
    - ./data_source:/opt/airflow/data_source
    - ./frontend:/usr/share/nginx/html
    - ./config:/usr/share/nginx/html/config
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
      image: postgres:13
      container_name: lol-airflow-db
      environment:
        POSTGRES_USER: airflow
        POSTGRES_PASSWORD: airflow
        POSTGRES_DB: airflow
      # 👇 1. DB의 데이터를 영구 저장할 볼륨을 컨테이너에 연결해줘
      volumes:
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U airflow"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
      - lol-network

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: lol-airflow-webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - lol-network

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: lol-airflow-scheduler
    networks:
      - lol-network

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    networks:
      - lol-network

  # 1. 프론트엔드 서비스 추가
  frontend:
    image: nginx:alpine  # 아주 가볍고 빠른 웹 서버야
    container_name: lol-frontend
    ports:
      - "80:80"  # 내 컴퓨터의 80번 포트로 접속하면 도커 안의 80번(프론트)으로 연결돼
    volumes:
      - ./frontend:/usr/share/nginx/html  # 은비의 로컬 frontend 폴더를 도커에 동기화해
    networks:
      - lol-network
networks:
  lol-network:
    driver: bridge

volumes:
  postgres-data: