version: '3.8'

services:
  # 1. 은비의 데이터 기지 (PostgreSQL)
  db:
    image: postgres:15
    container_name: lol_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eunbee
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lol_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # 2. 은비의 컨베이어 벨트 (Airflow)
  airflow:
    image: apache/airflow:2.7.1
    container_name: lol_airflow
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://eunbee:postgres@db:5432/lol_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_USERNAME=airflow  # 은비 아이디로!
      - _AIRFLOW_WWW_USER_PASSWORD=airflow    # 은비 비번으로!
    volumes:
      - ./dags:/opt/airflow/dags        # 은비의 dags 폴더와 동기화
      - ./scripts:/opt/airflow/scripts  # scripts 폴더와 동기화
    ports:
      - "8080:8080"
    command: standalone

volumes:
  postgres_data: